<a href="https://colab.research.google.com/github/CyberNelson/Python-Tutor/blob/main/Bandit_Levels_0_to_12_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install paramiko

Collecting paramiko
  Downloading paramiko-2.8.0-py2.py3-none-any.whl (206 kB)
     |████████████████████████████████| 206 kB 21.6 MB/s
Collecting cryptography>=2.5
  Downloading cryptography-35.0.0-cp36-abi3-manylinux_2_24_x86_64.whl (3.5 MB)
     |████████████████████████████████| 3.5 MB 32.4 MB/s
Collecting bcrypt>=3.1.3
  Downloading bcrypt-3.2.0-cp36-abi3-manylinux2010_x86_64.whl (63 kB)
     |████████████████████████████████| 63 kB 2.6 MB/s
Collecting pynacl>=1.0.1
  Downloading PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl (961 kB)
     |████████████████████████████████| 961 kB 39.8 MB/s
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from bcrypt>=3.1.3->paramiko) (1.15.0)
Requirement already satisfied: cffi>=1.1 in /usr/local/lib/python3.7/dist-packages (from bcrypt>=3.1.3->paramiko) (1.14.6)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko) (2.20)
Installing collected packages: pynacl, cryptography, bcrypt, paramiko
Successfully installed bcrypt-3.2.0 cryptography-35.0.0 paramiko-2.8.0 pynacl-1.4.0

# Bandit Level 0 ==> Level 1

Part A
--Level Goal--
    The goal of this level is for you to log into the game using SSH. The host to which you need to connect is bandit.labs.overthewire.org, on port 2220. The username is bandit0 and the password is bandit0. Once logged in, go to the Level 1 page to find out how to beat Level 1.

--Commands you may need to solve this level--
    ssh

--Helpful Reading Material--
-Secure Shell (SSH) on Wikipedia
-How to use SSH on wikiHow

Part B
--Level Goal--
    The password for the next level is stored in a file called readme located in the home directory. Use this password to log into bandit1 using SSH. Whenever you find a password for a level, use SSH (on port 2220) to log into that level and continue the game.

--Commands you may need to solve this level--
    ls, cd, cat, file, du, find
    
--Results--
Password:  boJ9jbbUNNfktd78OOpsqOltutMc3MY1

In [ ]:
import paramiko
import pandas as pd
import datetime
class SSH:
    def __init__(self,host,port,username,password):
        self.host=host
        self.port=port
        self.username=username
        self.password=password
        self.connection=self.__connect__()
        self.log={"Time Of Execution":[],"Command":[],"Results Decoded":[],"Results Encoded":[],"Results Size (Bytes)":[]}
    def __connect__(self):
        print("Starting Up SSH Client...")
        ssh=paramiko.SSHClient()
        print("Complete\nAdding Auto Add Policy...")
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        print("Complete\nAuthorizing Connection...")
        ssh.connect(self.host,port=self.port,username=self.username,password=self.password)
        print("Complete...\nConnected!\n==========\n\n")
        return ssh
    def Execute(self,command=None):
        print("Executing command: "+str(command))
        ssh_stdin, ssh_stdout, ssh_stderr = self.connection.exec_command(command)
        print("Command Executed...\nLogging Data...")
        Time=str(datetime.datetime.now())
        self.log["Time Of Execution"].append(Time)
        self.log["Command"].append(command)
        try:
            decoded_data=ssh_stdout.read().decode("ascii")
        except:
            decoded_data=None
        try:
            size=len(decoded_data)
        except:
            size=0
        self.log["Results Decoded"].append(decoded_data)
        self.log["Results Encoded"].append(repr(ssh_stdout.read()))
        self.log["Results Size (Bytes)"].append(size)
        print("Data Logged...\nComplete!\n\n--Executed Results--\nTime Of Execution: "+str(Time)+"\nCommand: "+command+"\nResults Size (Bytes): "+str(size)+"\nResults (Decoded): "+str(decoded_data)+"\nResults (Encoded): "+str(repr(ssh_stdout.read()))+"\n==========\n")
        return decoded_data
    def History(self):
        return pd.DataFrame(self.log)

print("Bandit: Level 0 -> Level 1\n==========")
server=SSH("bandit.labs.overthewire.org",2220,"bandit0","bandit0")
print("Password: ",server.Execute("cat readme")+"\n==========\nHistory")
server.History()

Bandit: Level 0 -> Level 1
==========
Starting Up SSH Client...
Complete
Adding Auto Add Policy...
Complete
Authorizing Connection...
Complete...
Connected!
==========


Executing command: cat readme
Command Executed...
Logging Data...
Data Logged...
Complete!

--Executed Results--
Time Of Execution: 2021-11-08 21:06:14.694688
Command: cat readme
Results Size (Bytes): 33
Results (Decoded): boJ9jbbUNNfktd78OOpsqOltutMc3MY1

Results (Encoded): b''
==========

Password:  boJ9jbbUNNfktd78OOpsqOltutMc3MY1

==========
History

,Time Of Execution,Command,Results Decoded,Results Encoded,Results Size (Bytes)
0,2021-11-08 21:06:14.694688,cat readme,boJ9jbbUNNfktd78OOpsqOltutMc3MY1\n,b'',33

# Bandit Level 1 ==> Level 2

--Level Goal--
    The password for the next level is stored in a file called - located in the home directory

--Commands you may need to solve this level--
    ls, cd, cat, file, du, find

--Helpful Reading Material--
-Google Search for “dashed filename”
-Advanced Bash-scripting Guide - Chapter 3 - Special Characters

--Results--
Password:  CV1DtqXWVFXTvM2F0k09SHz0YwRINYA9

In [ ]:
import paramiko
import pandas as pd
import datetime
class SSH:
    def __init__(self,host,port,username,password):
        self.host=host
        self.port=port
        self.username=username
        self.password=password
        self.connection=self.__connect__()
        self.log={"Time Of Execution":[],"Command":[],"Results Decoded":[],"Results Encoded":[],"Results Size (Bytes)":[]}
    def __connect__(self):
        print("Starting Up SSH Client...")
        ssh=paramiko.SSHClient()
        print("Complete\nAdding Auto Add Policy...")
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        print("Complete\nAuthorizing Connection...")
        ssh.connect(self.host,port=self.port,username=self.username,password=self.password)
        print("Complete...\nConnected!\n==========\n\n")
        return ssh
    def Execute(self,command=None):
        print("Executing command: "+str(command))
        ssh_stdin, ssh_stdout, ssh_stderr = self.connection.exec_command(command)
        print("Command Executed...\nLogging Data...")
        Time=str(datetime.datetime.now())
        self.log["Time Of Execution"].append(Time)
        self.log["Command"].append(command)
        try:
            decoded_data=ssh_stdout.read().decode("ascii")
        except:
            decoded_data=None
        try:
            size=len(decoded_data)
        except:
            size=0
        self.log["Results Decoded"].append(decoded_data)
        self.log["Results Encoded"].append(repr(ssh_stdout.read()))
        self.log["Results Size (Bytes)"].append(size)
        print("Data Logged...\nComplete!\n\n--Executed Results--\nTime Of Execution: "+str(Time)+"\nCommand: "+command+"\nResults Size (Bytes): "+str(size)+"\nResults (Decoded): "+str(decoded_data)+"\nResults (Encoded): "+str(repr(ssh_stdout.read()))+"\n==========\n")
        return decoded_data
    def History(self):
        return pd.DataFrame(self.log)

print("Bandit: Level 1 -> Level 2\n==========")
server=SSH("bandit.labs.overthewire.org",2220,"bandit1","boJ9jbbUNNfktd78OOpsqOltutMc3MY1")
print("Password: ",server.Execute("cat ./-")+"\n==========\nHistory")
server.History()

Bandit: Level 1 -> Level 2
==========
Starting Up SSH Client...
Complete
Adding Auto Add Policy...
Complete
Authorizing Connection...
Complete...
Connected!
==========


Executing command: cat ./-
Command Executed...
Logging Data...
Data Logged...
Complete!

--Executed Results--
Time Of Execution: 2021-11-08 21:15:39.306065
Command: cat ./-
Results Size (Bytes): 33
Results (Decoded): CV1DtqXWVFXTvM2F0k09SHz0YwRINYA9

Results (Encoded): b''
==========

Password:  CV1DtqXWVFXTvM2F0k09SHz0YwRINYA9

==========
History

,Time Of Execution,Command,Results Decoded,Results Encoded,Results Size (Bytes)
0,2021-11-08 21:15:39.306065,cat ./-,CV1DtqXWVFXTvM2F0k09SHz0YwRINYA9\n,b'',33

# Bandit Level 2 ==> Level 3

--Level Goal--
    The password for the next level is stored in a file called spaces in this filename located in the home directory

--Commands you may need to solve this level--
    ls, cd, cat, file, du, find

--Helpful Reading Material--
-Google Search for “spaces in filename”

--Results--
Password:  UmHadQclWmgdLOKQ3YNgjWxGoRMb5luK

In [ ]:
import paramiko
import pandas as pd
import datetime
class SSH:
    def __init__(self,host,port,username,password):
        self.host=host
        self.port=port
        self.username=username
        self.password=password
        self.connection=self.__connect__()
        self.log={"Time Of Execution":[],"Command":[],"Results Decoded":[],"Results Encoded":[],"Results Size (Bytes)":[]}
    def __connect__(self):
        print("Starting Up SSH Client...")
        ssh=paramiko.SSHClient()
        print("Complete\nAdding Auto Add Policy...")
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        print("Complete\nAuthorizing Connection...")
        ssh.connect(self.host,port=self.port,username=self.username,password=self.password)
        print("Complete...\nConnected!\n==========\n\n")
        return ssh
    def Execute(self,command=None):
        print("Executing command: "+str(command))
        ssh_stdin, ssh_stdout, ssh_stderr = self.connection.exec_command(command)
        print("Command Executed...\nLogging Data...")
        Time=str(datetime.datetime.now())
        self.log["Time Of Execution"].append(Time)
        self.log["Command"].append(command)
        try:
            decoded_data=ssh_stdout.read().decode("ascii")
        except:
            decoded_data=None
        try:
            size=len(decoded_data)
        except:
            size=0
        self.log["Results Decoded"].append(decoded_data)
        self.log["Results Encoded"].append(repr(ssh_stdout.read()))
        self.log["Results Size (Bytes)"].append(size)
        print("Data Logged...\nComplete!\n\n--Executed Results--\nTime Of Execution: "+str(Time)+"\nCommand: "+command+"\nResults Size (Bytes): "+str(size)+"\nResults (Decoded): "+str(decoded_data)+"\nResults (Encoded): "+str(repr(ssh_stdout.read()))+"\n==========\n")
        return decoded_data
    def History(self):
        return pd.DataFrame(self.log)

print("Bandit: Level 2 -> Level 3\n==========")
server=SSH("bandit.labs.overthewire.org",2220,"bandit2","CV1DtqXWVFXTvM2F0k09SHz0YwRINYA9")
print("Password: ",server.Execute("cat ./spaces\ in\ this\ filename")+"\n==========\nHistory")
server.History()

Bandit: Level 2 -> Level 3
==========
Starting Up SSH Client...
Complete
Adding Auto Add Policy...
Complete
Authorizing Connection...
Complete...
Connected!
==========


Executing command: cat ./spaces\ in\ this\ filename
Command Executed...
Logging Data...
Data Logged...
Complete!

--Executed Results--
Time Of Execution: 2021-11-09 13:17:16.821710
Command: cat ./spaces\ in\ this\ filename
Results Size (Bytes): 33
Results (Decoded): UmHadQclWmgdLOKQ3YNgjWxGoRMb5luK

Results (Encoded): b''
==========

Password:  UmHadQclWmgdLOKQ3YNgjWxGoRMb5luK

==========
History

            Time Of Execution  ... Results Size (Bytes)
0  2021-11-09 13:17:16.821710  ...                   33

[1 rows x 5 columns]

# Bandit Level 3 ==> Level 4

--Level Goal--
    The password for the next level is stored in a hidden file in the inhere directory.

--Commands you may need to solve this level--
    ls, cd, cat, file, du, find

--Results--
Password: pIwrPrtPN36QITSp3EQaw936yaFoFgAB

In [ ]:
import paramiko
import pandas as pd
import datetime
class SSH:
    def __init__(self,host,port,username,password):
        self.host=host
        self.port=port
        self.username=username
        self.password=password
        self.connection=self.__connect__()
        self.log={"Time Of Execution":[],"Command":[],"Results Decoded":[],"Results Encoded":[],"Results Size (Bytes)":[]}
    def __connect__(self):
        print("Starting Up SSH Client...")
        ssh=paramiko.SSHClient()
        print("Complete\nAdding Auto Add Policy...")
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        print("Complete\nAuthorizing Connection...")
        ssh.connect(self.host,port=self.port,username=self.username,password=self.password)
        print("Complete...\nConnected!\n==========\n\n")
        return ssh
    def Execute(self,command=None):
        print("Executing command: "+str(command))
        ssh_stdin, ssh_stdout, ssh_stderr = self.connection.exec_command(command)
        print("Command Executed...\nLogging Data...")
        Time=str(datetime.datetime.now())
        self.log["Time Of Execution"].append(Time)
        self.log["Command"].append(command)
        try:
            decoded_data=ssh_stdout.read().decode("ascii")
        except:
            decoded_data=None
        try:
            size=len(decoded_data)
        except:
            size=0
        self.log["Results Decoded"].append(decoded_data)
        self.log["Results Encoded"].append(repr(ssh_stdout.read()))
        self.log["Results Size (Bytes)"].append(size)
        print("Data Logged...\nComplete!\n\n--Executed Results--\nTime Of Execution: "+str(Time)+"\nCommand: "+command+"\nResults Size (Bytes): "+str(size)+"\nResults (Decoded): "+str(decoded_data)+"\nResults (Encoded): "+str(repr(ssh_stdout.read()))+"\n==========\n")
        return decoded_data
    def History(self):
        return pd.DataFrame(self.log)

print("Bandit: Level 3 -> Level 4\n==========")
server=SSH("bandit.labs.overthewire.org",2220,"bandit3","UmHadQclWmgdLOKQ3YNgjWxGoRMb5luK")
files=server.Execute('find ./inhere -name "*"')
print("File List:")
print(files)
files=files.split("\n")
for i in files:
    if "./inhere/" not in i:
        files.remove(i)
        print("Removing Path: ",i)
print("Prepared File List For Execution:")
for i in files:
    print(i)
print("Investigating...")
for i in files:
    server.Execute("cat "+i)
print("\n==========\nHistory")
server.History()

Bandit: Level 3 -> Level 4
==========
Starting Up SSH Client...
Complete
Adding Auto Add Policy...
Complete
Authorizing Connection...
Complete...
Connected!
==========


Executing command: find ./inhere -name "*"
Command Executed...
Logging Data...
Data Logged...
Complete!

--Executed Results--
Time Of Execution: 2021-11-09 13:18:17.357936
Command: find ./inhere -name "*"
Results Size (Bytes): 26
Results (Decoded): ./inhere
./inhere/.hidden

Results (Encoded): b''
==========

File List:
./inhere
./inhere/.hidden

Removing Path:  ./inhere
Removing Path:
Prepared File List For Execution:
./inhere/.hidden
Investigating...
Executing command: cat ./inhere/.hidden
Command Executed...
Logging Data...
Data Logged...
Complete!

--Executed Results--
Time Of Execution: 2021-11-09 13:18:17.678074
Command: cat ./inhere/.hidden
Results Size (Bytes): 33
Results (Decoded): pIwrPrtPN36QITSp3EQaw936yaFoFgAB

Results (Encoded): b''
==========


==========
History

            Time Of Execution  ... Results Size (Bytes)
0  2021-11-09 13:18:17.357936  ...                   26
1  2021-11-09 13:18:17.678074  ...                   33

[2 rows x 5 columns]

# Bandit Level 4 ==> Level 5

--Level Goal--
    The password for the next level is stored in the only human-readable file in the inhere directory. Tip: if your terminal is messed up, try the “reset” command.

--Commands you may need to solve this level--
ls, cd, cat, file, du, find

--Results--
Password: koReBOKuIDDepwhWk7jZC0RTdopnAYKh

In [ ]:
import paramiko
import pandas as pd
import datetime
class SSH:
    def __init__(self,host,port,username,password):
        self.host=host
        self.port=port
        self.username=username
        self.password=password
        self.connection=self.__connect__()
        self.log={"Time Of Execution":[],"Command":[],"Results Decoded":[],"Results Encoded":[],"Results Size (Bytes)":[]}
    def __connect__(self):
        print("Starting Up SSH Client...")
        ssh=paramiko.SSHClient()
        print("Complete\nAdding Auto Add Policy...")
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        print("Complete\nAuthorizing Connection...")
        ssh.connect(self.host,port=self.port,username=self.username,password=self.password)
        print("Complete...\nConnected!\n==========\n\n")
        return ssh
    def Execute(self,command=None):
        print("Executing command: "+str(command))
        ssh_stdin, ssh_stdout, ssh_stderr = self.connection.exec_command(command)
        print("Command Executed...\nLogging Data...")
        Time=str(datetime.datetime.now())
        self.log["Time Of Execution"].append(Time)
        self.log["Command"].append(command)
        try:
            decoded_data=ssh_stdout.read().decode("ascii")
        except:
            decoded_data=None
        try:
            size=len(decoded_data)
        except:
            size=0
        self.log["Results Decoded"].append(decoded_data)
        self.log["Results Encoded"].append(repr(ssh_stdout.read()))
        self.log["Results Size (Bytes)"].append(size)
        print("Data Logged...\nComplete!\n\n--Executed Results--\nTime Of Execution: "+str(Time)+"\nCommand: "+command+"\nResults Size (Bytes): "+str(size)+"\nResults (Decoded): "+str(decoded_data)+"\nResults (Encoded): "+str(repr(ssh_stdout.read()))+"\n==========\n")
        return decoded_data
    def History(self):
        return pd.DataFrame(self.log)

print("Bandit: Level 4 -> Level 5\n==========")
server=SSH("bandit.labs.overthewire.org",2220,"bandit4","pIwrPrtPN36QITSp3EQaw936yaFoFgAB")
files=server.Execute('find ./inhere -name "*"')
print("File List:")
print(files)
files=files.split("\n")
for i in files:
    if "./inhere/" not in i:
        files.remove(i)
        print("Removing Path: ",i)
print("Prepared File List For Execution:")
for i in files:
    print(i)
print("Investigating...")
for i in files:
    server.Execute("cat "+i)
print("\n==========\nHistory")
server.History()

ModuleNotFoundError: ignored

# Bandit Level 5 ==> Level 6

--Level Goal--
    The password for the next level is stored in a file somewhere under the inhere directory and has all of the following properties:

-human-readable
-1033 bytes in size
-not executable

--Commands you may need to solve this level--
    ls, cd, cat, file, du, find

--Results--
Password: DXjZPULLxYr17uwoI01bNLQbtFemEgo7

In [ ]:
import paramiko
import pandas as pd
import datetime
class SSH:
    def __init__(self,host,port,username,password):
        self.host=host
        self.port=port
        self.username=username
        self.password=password
        self.connection=self.__connect__()
        self.log={"Time Of Execution":[],"Command":[],"Results Decoded":[],"Results Encoded":[],"Results Size (Bytes)":[]}
    def __connect__(self):
        print("Starting Up SSH Client...")
        ssh=paramiko.SSHClient()
        print("Complete\nAdding Auto Add Policy...")
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        print("Complete\nAuthorizing Connection...")
        ssh.connect(self.host,port=self.port,username=self.username,password=self.password)
        print("Complete...\nConnected!\n==========\n\n")
        return ssh
    def Execute(self,command=None):
        print("Executing command: "+str(command))
        ssh_stdin, ssh_stdout, ssh_stderr = self.connection.exec_command(command)
        print("Command Executed...\nLogging Data...")
        Time=str(datetime.datetime.now())
        self.log["Time Of Execution"].append(Time)
        self.log["Command"].append(command)
        try:
            decoded_data=ssh_stdout.read().decode("ascii")
        except:
            decoded_data=None
        try:
            size=len(decoded_data)
        except:
            size=0
        self.log["Results Decoded"].append(decoded_data)
        self.log["Results Encoded"].append(repr(ssh_stdout.read()))
        self.log["Results Size (Bytes)"].append(size)
        print("Data Logged...\nComplete!\n\n--Executed Results--\nTime Of Execution: "+str(Time)+"\nCommand: "+command+"\nResults Size (Bytes): "+str(size)+"\nResults (Decoded): "+str(decoded_data)+"\nResults (Encoded): "+str(repr(ssh_stdout.read()))+"\n==========\n")
        return decoded_data
    def History(self):
        return pd.DataFrame(self.log)

print("Bandit: Level 5 -> Level 6\n==========")
server=SSH("bandit.labs.overthewire.org",2220,"bandit5","koReBOKuIDDepwhWk7jZC0RTdopnAYKh")
files=server.Execute('find ./inhere -name "*"')
print("File List:")
print(files)
files=files.split("\n")
for i in files:
    if "./inhere/" not in i:
        files.remove(i)
        print("Removing Path: ",i)
print("Prepared File List For Execution:")
for i in files:
    print(i)
print("Investigating...")
for i in files:
    server.Execute("cat "+i)
print("\n==========\nHistory")
server.History()[server.History()["Results Size (Bytes)"]==1033]

Bandit: Level 3 -> Level 4
==========
Starting Up SSH Client...
Complete
Adding Auto Add Policy...
Complete
Authorizing Connection...
Complete...
Connected!
==========


Executing command: find ./inhere -name "*"
Command Executed...
Logging Data...
Data Logged...
Complete!

--Executed Results--
Time Of Execution: 2021-11-09 13:17:40.419181
Command: find ./inhere -name "*"
Results Size (Bytes): 5829
Results (Decoded): ./inhere
./inhere/maybehere03
./inhere/maybehere03/.file2
./inhere/maybehere03/spaces file3
./inhere/maybehere03/-file3
./inhere/maybehere03/-file2
./inhere/maybehere03/.file3
./inhere/maybehere03/spaces file1
./inhere/maybehere03/-file1
./inhere/maybehere03/spaces file2
./inhere/maybehere03/.file1
./inhere/maybehere19
./inhere/maybehere19/.file2
./inhere/maybehere19/spaces file3
./inhere/maybehere19/-file3
./inhere/maybehere19/-file2
./inhere/maybehere19/.file3
./inhere/maybehere19/spaces file1
./inhere/maybehere19/-file1
./inhere/maybehere19/spaces file2
./inhere/maybehere19/.file1
./inhere/maybehere06
./inhere/maybehere06/.file2
./inhere/maybehere06/spaces file3
./inhere/maybehere06/-file3
./inhere/maybehere06/-file2
./inhere/maybehere06/.file3
./inhere/maybehere06/spaces file1
./inhere/maybehere06/-file1
./inhere/maybehere06/spaces file2
./inhere/maybehere06/.file1
./inhere/maybehere12
./inhere/maybehere12/.file2
./inhere/maybehere12/spaces file3
./inhere/maybehere12/-file3
./inhere/maybehere12/-file2
./inhere/maybehere12/.file3
./inhere/maybehere12/spaces file1
./inhere/maybehere12/-file1
./inhere/maybehere12/spaces file2
./inhere/maybehere12/.file1
./inhere/maybehere16
./inhere/maybehere16/.file2
./inhere/maybehere16/spaces file3
./inhere/maybehere16/-file3
./inhere/maybehere16/-file2
./inhere/maybehere16/.file3
./inhere/maybehere16/spaces file1
./inhere/maybehere16/-file1
./inhere/maybehere16/spaces file2
./inhere/maybehere16/.file1
./inhere/maybehere02
./inhere/maybehere02/.file2
./inhere/maybehere02/spaces file3
./inhere/maybehere02/-file3
./inhere/maybehere02/-file2
./inhere/maybehere02/.file3
./inhere/maybehere02/spaces file1
./inhere/maybehere02/-file1
./inhere/maybehere02/spaces file2
./inhere/maybehere02/.file1
./inhere/maybehere01
./inhere/maybehere01/.file2
./inhere/maybehere01/spaces file3
./inhere/maybehere01/-file3
./inhere/maybehere01/-file2
./inhere/maybehere01/.file3
./inhere/maybehere01/spaces file1
./inhere/maybehere01/-file1
./inhere/maybehere01/spaces file2
./inhere/maybehere01/.file1
./inhere/maybehere17
./inhere/maybehere17/.file2
./inhere/maybehere17/spaces file3
./inhere/maybehere17/-file3
./inhere/maybehere17/-file2
./inhere/maybehere17/.file3
./inhere/maybehere17/spaces file1
./inhere/maybehere17/-file1
./inhere/maybehere17/spaces file2
./inhere/maybehere17/.file1
./inhere/maybehere04
./inhere/maybehere04/.file2
./inhere/maybehere04/spaces file3
./inhere/maybehere04/-file3
./inhere/maybehere04/-file2
./inhere/maybehere04/.file3
./inhere/maybehere04/spaces file1
./inhere/maybehere04/-file1
./inhere/maybehere04/spaces file2
./inhere/maybehere04/.file1
./inhere/maybehere11
./inhere/maybehere11/.file2
./inhere/maybehere11/spaces file3
./inhere/maybehere11/-file3
./inhere/maybehere11/-file2
./inhere/maybehere11/.file3
./inhere/maybehere11/spaces file1
./inhere/maybehere11/-file1
./inhere/maybehere11/spaces file2
./inhere/maybehere11/.file1
./inhere/maybehere09
./inhere/maybehere09/.file2
./inhere/maybehere09/spaces file3
./inhere/maybehere09/-file3
./inhere/maybehere09/-file2
./inhere/maybehere09/.file3
./inhere/maybehere09/spaces file1
./inhere/maybehere09/-file1
./inhere/maybehere09/spaces file2
./inhere/maybehere09/.file1
./inhere/maybehere15
./inhere/maybehere15/.file2
./inhere/maybehere15/spaces file3
./inhere/maybehere15/-file3
./inhere/maybehere15/-file2
./inhere/maybehere15/.file3
./inhere/maybehere15/spaces file1
./inhere/maybehere15/-file1
./inhere/maybehere15/spaces file2
./inhere/maybehere15/.file1
./inhere/maybehere08
./inhere/maybehere08/.file2
./inhere/maybehere08/spaces file3
./inhere/maybehere08/-file3
./inhere/maybehere08/-file2
./inhere/maybehere08/.file3
./inhere/maybehere08/spaces file1
./inhere/maybehere08/-file1
./inhere/maybehere08/spaces file2
./inhere/maybehere08/.file1
./inhere/maybehere14
./inhere/maybehere14/.file2
./inhere/maybehere14/spaces file3
./inhere/maybehere14/-file3
./inhere/maybehere14/-file2
./inhere/maybehere14/.file3
./inhere/maybehere14/spaces file1
./inhere/maybehere14/-file1
./inhere/maybehere14/spaces file2
./inhere/maybehere14/.file1
./inhere/maybehere00
./inhere/maybehere00/.file2
./inhere/maybehere00/spaces file3
./inhere/maybehere00/-file3
./inhere/maybehere00/-file2
./inhere/maybehere00/.file3
./inhere/maybehere00/spaces file1
./inhere/maybehere00/-file1
./inhere/maybehere00/spaces file2
./inhere/maybehere00/.file1
./inhere/maybehere18
./inhere/maybehere18/.file2
./inhere/maybehere18/spaces file3
./inhere/maybehere18/-file3
./inhere/maybehere18/-file2
./inhere/maybehere18/.file3
./inhere/maybehere18/spaces file1
./inhere/maybehere18/-file1
./inhere/maybehere18/spaces file2
./inhere/maybehere18/.file1
./inhere/maybehere05
./inhere/maybehere05/.file2
./inhere/maybehere05/spaces file3
./inhere/maybehere05/-file3
./inhere/maybehere05/-file2
./inhere/maybehere05/.file3
./inhere/maybehere05/spaces file1
./inhere/maybehere05/-file1
./inhere/maybehere05/spaces file2
./inhere/maybehere05/.file1
./inhere/maybehere07
./inhere/maybehere07/.file2
./inhere/maybehere07/spaces file3
./inhere/maybehere07/-file3
./inhere/maybehere07/-file2
./inhere/maybehere07/.file3
./inhere/maybehere07/spaces file1
./inhere/maybehere07/-file1
./inhere/maybehere07/spaces file2
./inhere/maybehere07/.file1
./inhere/maybehere10
./inhere/maybehere10/.file2
./inhere/maybehere10/spaces file3
./inhere/maybehere10/-file3
./inhere/maybehere10/-file2
./inhere/maybehere10/.file3
./inhere/maybehere10/spaces file1
./inhere/maybehere10/-file1
./inhere/maybehere10/spaces file2
./inhere/maybehere10/.file1
./inhere/maybehere13
./inhere/maybehere13/.file2
./inhere/maybehere13/spaces file3
./inhere/maybehere13/-file3
./inhere/maybehere13/-file2
./inhere/maybehere13/.file3
./inhere/maybehere13/spaces file1
./inhere/maybehere13/-file1
./inhere/maybehere13/spaces file2
./inhere/maybehere13/.file1

Results (Encoded): b''
==========

File List:
./inhere
./inhere/maybehere03
./inhere/maybehere03/.file2
./inhere/maybehere03/spaces file3
./inhere/maybehere03/-file3
./inhere/maybehere03/-file2
./inhere/maybehere03/.file3
./inhere/maybehere03/spaces file1
./inhere/maybehere03/-file1
./inhere/maybehere03/spaces file2
./inhere/maybehere03/.file1
./inhere/maybehere19
./inhere/maybehere19/.file2
./inhere/maybehere19/spaces file3
./inhere/maybehere19/-file3
./inhere/maybehere19/-file2
./inhere/maybehere19/.file3
./inhere/maybehere19/spaces file1
./inhere/maybehere19/-file1
./inhere/maybehere19/spaces file2
./inhere/maybehere19/.file1
./inhere/maybehere06
./inhere/maybehere06/.file2
./inhere/maybehere06/spaces file3
./inhere/maybehere06/-file3
./inhere/maybehere06/-file2
./inhere/maybehere06/.file3
./inhere/maybehere06/spaces file1
./inhere/maybehere06/-file1
./inhere/maybehere06/spaces file2
./inhere/maybehere06/.file1
./inhere/maybehere12
./inhere/maybehere12/.file2
./inhere/maybehere12/spaces file3
./inhere/maybehere12/-file3
./inhere/maybehere12/-file2
./inhere/maybehere12/.file3
./inhere/maybehere12/spaces file1
./inhere/maybehere12/-file1
./inhere/maybehere12/spaces file2
./inhere/maybehere12/.file1
./inhere/maybehere16
./inhere/maybehere16/.file2
./inhere/maybehere16/spaces file3
./inhere/maybehere16/-file3
./inhere/maybehere16/-file2
./inhere/maybehere16/.file3
./inhere/maybehere16/spaces file1
./inhere/maybehere16/-file1
./inhere/maybehere16/spaces file2
./inhere/maybehere16/.file1
./inhere/maybehere02
./inhere/maybehere02/.file2
./inhere/maybehere02/spaces file3
./inhere/maybehere02/-file3
./inhere/maybehere02/-file2
./inhere/maybehere02/.file3
./inhere/maybehere02/spaces file1
./inhere/maybehere02/-file1
./inhere/maybehere02/spaces file2
./inhere/maybehere02/.file1
./inhere/maybehere01
./inhere/maybehere01/.file2
./inhere/maybehere01/spaces file3
./inhere/maybehere01/-file3
./inhere/maybehere01/-file2
./inhere/maybehere01/.file3
./inhere/maybehere01/spaces file1
./inhere/maybehere01/-file1
./inhere/maybehere01/spaces file2
./inhere/maybehere01/.file1
./inhere/maybehere17
./inhere/maybehere17/.file2
./inhere/maybehere17/spaces file3
./inhere/maybehere17/-file3
./inhere/maybehere17/-file2
./inhere/maybehere17/.file3
./inhere/maybehere17/spaces file1
./inhere/maybehere17/-file1
./inhere/maybehere17/spaces file2
./inhere/maybehere17/.file1
./inhere/maybehere04
./inhere/maybehere04/.file2
./inhere/maybehere04/spaces file3
./inhere/maybehere04/-file3
./inhere/maybehere04/-file2
./inhere/maybehere04/.file3
./inhere/maybehere04/spaces file1
./inhere/maybehere04/-file1
./inhere/maybehere04/spaces file2
./inhere/maybehere04/.file1
./inhere/maybehere11
./inhere/maybehere11/.file2
./inhere/maybehere11/spaces file3
./inhere/maybehere11/-file3
./inhere/maybehere11/-file2
./inhere/maybehere11/.file3
./inhere/maybehere11/spaces file1
./inhere/maybehere11/-file1
./inhere/maybehere11/spaces file2
./inhere/maybehere11/.file1
./inhere/maybehere09
./inhere/maybehere09/.file2
./inhere/maybehere09/spaces file3
./inhere/maybehere09/-file3
./inhere/maybehere09/-file2
./inhere/maybehere09/.file3
./inhere/maybehere09/spaces file1
./inhere/maybehere09/-file1
./inhere/maybehere09/spaces file2
./inhere/maybehere09/.file1
./inhere/maybehere15
./inhere/maybehere15/.file2
./inhere/maybehere15/spaces file3
./inhere/maybehere15/-file3
./inhere/maybehere15/-file2
./inhere/maybehere15/.file3
./inhere/maybehere15/spaces file1
./inhere/maybehere15/-file1
./inhere/maybehere15/spaces file2
./inhere/maybehere15/.file1
./inhere/maybehere08
./inhere/maybehere08/.file2
./inhere/maybehere08/spaces file3
./inhere/maybehere08/-file3
./inhere/maybehere08/-file2
./inhere/maybehere08/.file3
./inhere/maybehere08/spaces file1
./inhere/maybehere08/-file1
./inhere/maybehere08/spaces file2
./inhere/maybehere08/.file1
./inhere/maybehere14
./inhere/maybehere14/.file2
./inhere/maybehere14/spaces file3
./inhere/maybehere14/-file3
./inhere/maybehere14/-file2
./inhere/maybehere14/.file3
./inhere/maybehere14/spaces file1
./inhere/maybehere14/-file1
./inhere/maybehere14/spaces file2
./inhere/maybehere14/.file1
./inhere/maybehere00
./inhere/maybehere00/.file2
./inhere/maybehere00/spaces file3
./inhere/maybehere00/-file3
./inhere/maybehere00/-file2
./inhere/maybehere00/.file3
./inhere/maybehere00/spaces file1
./inhere/maybehere00/-file1
./inhere/maybehere00/spaces file2
./inhere/maybehere00/.file1
./inhere/maybehere18
./inhere/maybehere18/.file2
./inhere/maybehere18/spaces file3
./inhere/maybehere18/-file3
./inhere/maybehere18/-file2
./inhere/maybehere18/.file3
./inhere/maybehere18/spaces file1
./inhere/maybehere18/-file1
./inhere/maybehere18/spaces file2
./inhere/maybehere18/.file1
./inhere/maybehere05
./inhere/maybehere05/.file2
./inhere/maybehere05/spaces file3
./inhere/maybehere05/-file3
./inhere/maybehere05/-file2
./inhere/maybehere05/.file3
./inhere/maybehere05/spaces file1
./inhere/maybehere05/-file1
./inhere/maybehere05/spaces file2
./inhere/maybehere05/.file1
./inhere/maybehere07
./inhere/maybehere07/.file2
./inhere/maybehere07/spaces file3
./inhere/maybehere07/-file3
./inhere/maybehere07/-file2
./inhere/maybehere07/.file3
./inhere/maybehere07/spaces file1
./inhere/maybehere07/-file1
./inhere/maybehere07/spaces file2
./inhere/maybehere07/.file1
./inhere/maybehere10
./inhere/maybehere10/.file2
./inhere/maybehere10/spaces file3
./inhere/maybehere10/-file3
./inhere/maybehere10/-file2
./inhere/maybehere10/.file3
./inhere/maybehere10/spaces file1
./inhere/maybehere10/-file1
./inhere/maybehere10/spaces file2
./inhere/maybehere10/.file1
./inhere/maybehere13
./inhere/maybehere13/.file2
./inhere/maybehere13/spaces file3
./inhere/maybehere13/-file3
./inhere/maybehere13/-file2
./inhere/maybehere13/.file3
./inhere/maybehere13/spaces file1
./inhere/maybehere13/-file1
./inhere/maybehere13/spaces file2
./inhere/maybehere13/.file1

Removing Path:  ./inhere
Removing Path:
Prepared File List For Execution:
./inhere/maybehere03
./inhere/maybehere03/.file2
./inhere/maybehere03/spaces file3
./inhere/maybehere03/-file3
./inhere/maybehere03/-file2
./inhere/maybehere03/.file3
./inhere/maybehere03/spaces file1
./inhere/maybehere03/-file1
./inhere/maybehere03/spaces file2
./inhere/maybehere03/.file1
./inhere/maybehere19
./inhere/maybehere19/.file2
./inhere/maybehere19/spaces file3
./inhere/maybehere19/-file3
./inhere/maybehere19/-file2
./inhere/maybehere19/.file3
./inhere/maybehere19/spaces file1
./inhere/maybehere19/-file1
./inhere/maybehere19/spaces file2
./inhere/maybehere19/.file1
./inhere/maybehere06
./inhere/maybehere06/.file2
./inhere/maybehere06/spaces file3
./inhere/maybehere06/-file3
./inhere/maybehere06/-file2
./inhere/maybehere06/.file3
./inhere/maybehere06/spaces file1
./inhere/maybehere06/-file1
./inhere/maybehere06/spaces file2
./inhere/maybehere06/.file1
./inhere/maybehere12
./inhere/maybehere12/.file2
./inhere/maybehere12/spaces file3
./inhere/maybehere12/-file3
./inhere/maybehere12/-file2
./inhere/maybehere12/.file3
./inhere/maybehere12/spaces file1
./inhere/maybehere12/-file1
./inhere/maybehere12/spaces file2
./inhere/maybehere12/.file1
./inhere/maybehere16
./inhere/maybehere16/.file2
./inhere/maybehere16/spaces file3
./inhere/maybehere16/-file3
./inhere/maybehere16/-file2
./inhere/maybehere16/.file3
./inhere/maybehere16/spaces file1
./inhere/maybehere16/-file1
./inhere/maybehere16/spaces file2
./inhere/maybehere16/.file1
./inhere/maybehere02
./inhere/maybehere02/.file2
./inhere/maybehere02/spaces file3
./inhere/maybehere02/-file3
./inhere/maybehere02/-file2
./inhere/maybehere02/.file3
./inhere/maybehere02/spaces file1
./inhere/maybehere02/-file1
./inhere/maybehere02/spaces file2
./inhere/maybehere02/.file1
./inhere/maybehere01
./inhere/maybehere01/.file2
./inhere/maybehere01/spaces file3
./inhere/maybehere01/-file3
./inhere/maybehere01/-file2
./inhere/maybehere01/.file3
./inhere/maybehere01/spaces file1
./inhere/maybehere01/-file1
./inhere/maybehere01/spaces file2
./inhere/maybehere01/.file1
./inhere/maybehere17
./inhere/maybehere17/.file2
./inhere/maybehere17/spaces file3
./inhere/maybehere17/-file3
./inhere/maybehere17/-file2
./inhere/maybehere17/.file3
./inhere/maybehere17/spaces file1
./inhere/maybehere17/-file1
./inhere/maybehere17/spaces file2
./inhere/maybehere17/.file1
./inhere/maybehere04
./inhere/maybehere04/.file2
./inhere/maybehere04/spaces file3
./inhere/maybehere04/-file3
./inhere/maybehere04/-file2
./inhere/maybehere04/.file3
./inhere/maybehere04/spaces file1
./inhere/maybehere04/-file1
./inhere/maybehere04/spaces file2
./inhere/maybehere04/.file1
./inhere/maybehere11
./inhere/maybehere11/.file2
./inhere/maybehere11/spaces file3
./inhere/maybehere11/-file3
./inhere/maybehere11/-file2
./inhere/maybehere11/.file3
./inhere/maybehere11/spaces file1
./inhere/maybehere11/-file1
./inhere/maybehere11/spaces file2
./inhere/maybehere11/.file1
./inhere/maybehere09
./inhere/maybehere09/.file2
./inhere/maybehere09/spaces file3
./inhere/maybehere09/-file3
./inhere/maybehere09/-file2
./inhere/maybehere09/.file3
./inhere/maybehere09/spaces file1
./inhere/maybehere09/-file1
./inhere/maybehere09/spaces file2
./inhere/maybehere09/.file1
./inhere/maybehere15
./inhere/maybehere15/.file2
./inhere/maybehere15/spaces file3
./inhere/maybehere15/-file3
./inhere/maybehere15/-file2
./inhere/maybehere15/.file3
./inhere/maybehere15/spaces file1
./inhere/maybehere15/-file1
./inhere/maybehere15/spaces file2
./inhere/maybehere15/.file1
./inhere/maybehere08
./inhere/maybehere08/.file2
./inhere/maybehere08/spaces file3
./inhere/maybehere08/-file3
./inhere/maybehere08/-file2
./inhere/maybehere08/.file3
./inhere/maybehere08/spaces file1
./inhere/maybehere08/-file1
./inhere/maybehere08/spaces file2
./inhere/maybehere08/.file1
./inhere/maybehere14
./inhere/maybehere14/.file2
./inhere/maybehere14/spaces file3
./inhere/maybehere14/-file3
./inhere/maybehere14/-file2
./inhere/maybehere14/.file3
./inhere/maybehere14/spaces file1
./inhere/maybehere14/-file1
./inhere/maybehere14/spaces file2
./inhere/maybehere14/.file1
./inhere/maybehere00
./inhere/maybehere00/.file2
./inhere/maybehere00/spaces file3
./inhere/maybehere00/-file3
./inhere/maybehere00/-file2
./inhere/maybehere00/.file3
./inhere/maybehere00/spaces file1
./inhere/maybehere00/-file1
./inhere/maybehere00/spaces file2
./inhere/maybehere00/.file1
./inhere/maybehere18
./inhere/maybehere18/.file2
./inhere/maybehere18/spaces file3
./inhere/maybehere18/-file3
./inhere/maybehere18/-file2
./inhere/maybehere18/.file3
./inhere/maybehere18/spaces file1
./inhere/maybehere18/-file1
./inhere/maybehere18/spaces file2
./inhere/maybehere18/.file1
./inhere/maybehere05
./inhere/maybehere05/.file2
./inhere/maybehere05/spaces file3
./inhere/maybehere05/-file3
./inhere/maybehere05/-file2
./inhere/maybehere05/.file3
./inhere/maybehere05/spaces file1
./inhere/maybehere05/-file1
./inhere/maybehere05/spaces file2
./inhere/maybehere05/.file1
./inhere/maybehere07
./inhere/maybehere07/.file2
./inhere/maybehere07/spaces file3
./inhere/maybehere07/-file3
./inhere/maybehere07/-file2
./inhere/maybehere07/.file3
./inhere/maybehere07/spaces file1
./inhere/maybehere07/-file1
./inhere/maybehere07/spaces file2
./inhere/maybehere07/.file1
./inhere/maybehere10
./inhere/maybehere10/.file2
./inhere/maybehere10/spaces file3
./inhere/maybehere10/-file3
./inhere/maybehere10/-file2
./inhere/maybehere10/.file3
./inhere/maybehere10/spaces file1
./inhere/maybehere10/-file1
./inhere/maybehere10/spaces file2
./inhere/maybehere10/.file1
./inhere/maybehere13
./inhere/maybehere13/.file2
./inhere/maybehere13/spaces file3
./inhere/maybehere13/-file3
./inhere/maybehere13/-file2
./inhere/maybehere13/.file3
./inhere/maybehere13/spaces file1
./inhere/maybehere13/-file1
./inhere/maybehere13/spaces file2
./inhere/maybehere13/.file1
Investigating...
Executing command: cat ./inhere/maybehere03
Command Executed...
Logging Data...
Data Logged...
Complete!

--Executed Results--
Time Of Execution: 2021-11-09 13:17:40.737088
Command: cat ./inhere/maybehere03
Results Size (Bytes): 0
Results (Decoded):
Results (Encoded): b''
==========

Executing command: cat ./inhere/maybehere03/.file2
Command Executed...
Logging Data...
Data Logged...
Complete!

--Executed Results--
Time Of Execution: 2021-11-09 13:17:41.010982
Command: cat ./inhere/maybehere03/.file2
Results Size (Bytes): 8880

KeyboardInterrupt: ignored

#Bandit Level 6 ==> Level 7
--Level Goal--

  The password for the next level is stored somewhere on the server and has all of the following properties:

-owned by user bandit7

-owned by group bandit6

-33 bytes in size

--Commands you may need to solve this level--

  ls, cd, cat, file, du, find, grep

--Results--

Password: HKBPTKQnIay4Fw76bEy8PVxKEDQRKTzs

In [ ]:
import paramiko
import pandas as pd
import datetime
class SSH:
    def __init__(self,host,port,username,password):
        self.host=host
        self.port=port
        self.username=username
        self.password=password
        self.connection=self.__connect__()
        self.log={"Time Of Execution":[],"Command":[],"Results Decoded":[],"Results Encoded":[],"Results Size (Bytes)":[]}
    def __connect__(self):
        print("Starting Up SSH Client...")
        ssh=paramiko.SSHClient()
        print("Complete\nAdding Auto Add Policy...")
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        print("Complete\nAuthorizing Connection...")
        ssh.connect(self.host,port=self.port,username=self.username,password=self.password)
        print("Complete...\nConnected!\n==========\n\n")
        return ssh
    def Execute(self,command=None):
        print("Executing command: "+str(command))
        ssh_stdin, ssh_stdout, ssh_stderr = self.connection.exec_command(command)
        print("Command Executed...\nLogging Data...")
        Time=str(datetime.datetime.now())
        self.log["Time Of Execution"].append(Time)
        self.log["Command"].append(command)
        try:
            decoded_data=ssh_stdout.read().decode("ascii")
        except:
            decoded_data=None
        try:
            size=len(decoded_data)
        except:
            size=0
        self.log["Results Decoded"].append(decoded_data)
        self.log["Results Encoded"].append(repr(ssh_stdout.read()))
        self.log["Results Size (Bytes)"].append(size)
        print("Data Logged...\nComplete!\n\n--Executed Results--\nTime Of Execution: "+str(Time)+"\nCommand: "+command+"\nResults Size (Bytes): "+str(size)+"\nResults (Decoded): "+str(decoded_data)+"\nResults (Encoded): "+str(repr(ssh_stdout.read()))+"\n==========\n")
        return decoded_data
    def History(self):
        return pd.DataFrame(self.log)

print("Bandit: Level 6 -> Level 7\n==========")
server=SSH("bandit.labs.overthewire.org",2220,"bandit6","DXjZPULLxYr17uwoI01bNLQbtFemEgo7")
files=server.Execute('find / -user bandit7 -group bandit6 -size 33c')
print("File List:")
print(files)
files=files.split("\n")
print("Prepared File List For Execution:")
for i in files:
    print(i)
print("Investigating...")
for i in files:
    server.Execute("cat "+i)
print("\n==========\nHistory")
server.History()[server.History()["Results Size (Bytes)"]==33]

KeyboardInterrupt: ignored

#Bandit Level 7 ==> Level 8

--Level Goal--

The password for the next level is stored in the file data.txt next to the word millionth

--Commands you may need to solve this level--

grep, sort, uniq, strings, base64, tr, tar, gzip, bzip2, xxd

--Results--

Password: cvX2JJa4CFALtqS87jk27qwqGhBM9plV

In [ ]:
import paramiko
import pandas as pd
import datetime
class SSH:
    def __init__(self,host,port,username,password):
        self.host=host
        self.port=port
        self.username=username
        self.password=password
        self.connection=self.__connect__()
        self.log={"Time Of Execution":[],"Command":[],"Results Decoded":[],"Results Encoded":[],"Results Size (Bytes)":[]}
    def __connect__(self):
        print("Starting Up SSH Client...")
        ssh=paramiko.SSHClient()
        print("Complete\nAdding Auto Add Policy...")
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        print("Complete\nAuthorizing Connection...")
        ssh.connect(self.host,port=self.port,username=self.username,password=self.password)
        print("Complete...\nConnected!\n==========\n\n")
        return ssh
    def Execute(self,command=None):
        print("Executing command: "+str(command))
        ssh_stdin, ssh_stdout, ssh_stderr = self.connection.exec_command(command)
        print("Command Executed...\nLogging Data...")
        Time=str(datetime.datetime.now())
        self.log["Time Of Execution"].append(Time)
        self.log["Command"].append(command)
        try:
            decoded_data=ssh_stdout.read().decode("ascii")
        except:
            decoded_data=None
        try:
            size=len(decoded_data)
        except:
            size=0
        self.log["Results Decoded"].append(decoded_data)
        self.log["Results Encoded"].append(repr(ssh_stdout.read()))
        self.log["Results Size (Bytes)"].append(size)
        print("Data Logged...\nComplete!\n\n--Executed Results--\nTime Of Execution: "+str(Time)+"\nCommand: "+command+"\nResults Size (Bytes): "+str(size)+"\nResults (Decoded): "+str(decoded_data)+"\nResults (Encoded): "+str(ssh_stdout.read())+"\n==========\n")
        return decoded_data
    def History(self):
        return pd.DataFrame(self.log)

print("Bandit: Level 7 -> Level 8\n==========")
server=SSH("bandit.labs.overthewire.org",2220,"bandit7","HKBPTKQnIay4Fw76bEy8PVxKEDQRKTzs")
password=server.Execute('cat data.txt | grep "millionth"')
print(password)
print("\n==========\nHistory")
server.History()

Bandit: Level 7 -> Level 8
==========
Starting Up SSH Client...
Complete
Adding Auto Add Policy...
Complete
Authorizing Connection...
Complete...
Connected!
==========


Executing command: cat data.txt | grep "millionth"
Command Executed...
Logging Data...
Data Logged...
Complete!

--Executed Results--
Time Of Execution: 2021-11-09 14:02:14.583597
Command: cat data.txt | grep "millionth"
Results Size (Bytes): 43
Results (Decoded): millionth	cvX2JJa4CFALtqS87jk27qwqGhBM9plV

Results (Encoded): b''
==========

millionth	cvX2JJa4CFALtqS87jk27qwqGhBM9plV


==========
History

            Time Of Execution  ... Results Size (Bytes)
0  2021-11-09 14:02:14.583597  ...                   43

[1 rows x 5 columns]

#Bandit Level 8 ==> Level 9
--Level Goal--

The password for the next level is stored in the file data.txt and is the only line of text that occurs only once

--Commands you may need to solve this level--

grep, sort, uniq, strings, base64, tr, tar, gzip, bzip2, xxd

--Results--

Password: UsvVyFSfZZWbi6wgC7dAFyFuR6jQQUhR

In [ ]:
import paramiko
import pandas as pd
import datetime
class SSH:
    def __init__(self,host,port,username,password):
        self.host=host
        self.port=port
        self.username=username
        self.password=password
        self.connection=self.__connect__()
        self.log={"Time Of Execution":[],"Command":[],"Results Decoded":[],"Results Encoded":[],"Results Size (Bytes)":[]}
    def __connect__(self):
        print("Starting Up SSH Client...")
        ssh=paramiko.SSHClient()
        print("Complete\nAdding Auto Add Policy...")
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        print("Complete\nAuthorizing Connection...")
        ssh.connect(self.host,port=self.port,username=self.username,password=self.password)
        print("Complete...\nConnected!\n==========\n\n")
        return ssh
    def Execute(self,command=None):
        print("Executing command: "+str(command))
        ssh_stdin, ssh_stdout, ssh_stderr = self.connection.exec_command(command)
        print("Command Executed...\nLogging Data...")
        Time=str(datetime.datetime.now())
        self.log["Time Of Execution"].append(Time)
        self.log["Command"].append(command)
        try:
            decoded_data=ssh_stdout.read().decode("ascii")
        except:
            decoded_data=None
        try:
            size=len(decoded_data)
        except:
            size=0
        self.log["Results Decoded"].append(decoded_data)
        self.log["Results Encoded"].append(repr(ssh_stdout.read()))
        self.log["Results Size (Bytes)"].append(size)
        print("Data Logged...\nComplete!\n\n--Executed Results--\nTime Of Execution: "+str(Time)+"\nCommand: "+command+"\nResults Size (Bytes): "+str(size)+"\nResults (Decoded): "+str(decoded_data)+"\nResults (Encoded): "+str(ssh_stdout.read())+"\n==========\n")
        return decoded_data
    def History(self):
        return pd.DataFrame(self.log)

print("Bandit: Level 8 -> Level 9\n==========")
server=SSH("bandit.labs.overthewire.org",2220,"bandit8","cvX2JJa4CFALtqS87jk27qwqGhBM9plV")
password=server.Execute('cat data.txt | sort | uniq -u')
print(password)
print("\n==========\nHistory")
server.History()

Bandit: Level 8 -> Level 9
==========
Starting Up SSH Client...
Complete
Adding Auto Add Policy...
Complete
Authorizing Connection...
Complete...
Connected!
==========


Executing command: cat data.txt | sort | uniq -u
Command Executed...
Logging Data...
Data Logged...
Complete!

--Executed Results--
Time Of Execution: 2021-11-09 14:14:37.196594
Command: cat data.txt | sort | uniq -u
Results Size (Bytes): 33
Results (Decoded): UsvVyFSfZZWbi6wgC7dAFyFuR6jQQUhR

Results (Encoded): b''
==========

UsvVyFSfZZWbi6wgC7dAFyFuR6jQQUhR


==========
History

            Time Of Execution  ... Results Size (Bytes)
0  2021-11-09 14:14:37.196594  ...                   33

[1 rows x 5 columns]

#Bandit Level 9 ==> Level 10
--Level Goal--

The password for the next level is stored in the file data.txt in one of the few human-readable strings, preceded by several ‘=’ characters.

--Commands you may need to solve this level--

grep, sort, uniq, strings, base64, tr, tar, gzip, bzip2, xxd

--Results--

Password: truKLdjsbJ5g7yyJ2X2R0o3a5HQJFuLk

In [ ]:
import paramiko
import pandas as pd
import datetime
class SSH:
    def __init__(self,host,port,username,password):
        self.host=host
        self.port=port
        self.username=username
        self.password=password
        self.connection=self.__connect__()
        self.log={"Time Of Execution":[],"Command":[],"Results Decoded":[],"Results Encoded":[],"Results Size (Bytes)":[]}
    def __connect__(self):
        print("Starting Up SSH Client...")
        ssh=paramiko.SSHClient()
        print("Complete\nAdding Auto Add Policy...")
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        print("Complete\nAuthorizing Connection...")
        ssh.connect(self.host,port=self.port,username=self.username,password=self.password)
        print("Complete...\nConnected!\n==========\n\n")
        return ssh
    def Execute(self,command=None):
        print("Executing command: "+str(command))
        ssh_stdin, ssh_stdout, ssh_stderr = self.connection.exec_command(command)
        print("Command Executed...\nLogging Data...")
        Time=str(datetime.datetime.now())
        self.log["Time Of Execution"].append(Time)
        self.log["Command"].append(command)
        try:
            decoded_data=ssh_stdout.read().decode("ascii")
        except:
            decoded_data=None
        try:
            size=len(decoded_data)
        except:
            size=0
        self.log["Results Decoded"].append(decoded_data)
        self.log["Results Encoded"].append(repr(ssh_stdout.read()))
        self.log["Results Size (Bytes)"].append(size)
        print("Data Logged...\nComplete!\n\n--Executed Results--\nTime Of Execution: "+str(Time)+"\nCommand: "+command+"\nResults Size (Bytes): "+str(size)+"\nResults (Decoded): "+str(decoded_data)+"\nResults (Encoded): "+str(ssh_stdout.read())+"\n==========\n")
        return decoded_data
    def History(self):
        return pd.DataFrame(self.log)

print("Bandit: Level 9 -> Level 10\n==========")
server=SSH("bandit.labs.overthewire.org",2220,"bandit9","UsvVyFSfZZWbi6wgC7dAFyFuR6jQQUhR")
password=server.Execute('strings data.txt | grep -E "=+"')
print(password)
print("\n==========\nHistory")
server.History()

Bandit: Level 8 -> Level 9
==========
Starting Up SSH Client...
Complete
Adding Auto Add Policy...
Complete
Authorizing Connection...
Complete...
Connected!
==========


Executing command: strings data.txt | grep -E "=+"
Command Executed...
Logging Data...
Data Logged...
Complete!

--Executed Results--
Time Of Execution: 2021-11-09 14:47:11.832327
Command: strings data.txt | grep -E "=+"
Results Size (Bytes): 151
Results (Decoded): ========== the*2i"4
=:G e
========== password
<I=zsGi
Z)========== is
A=|t&E
Zdb=
c^ LAh=3G
*SF=s
&========== truKLdjsbJ5g7yyJ2X2R0o3a5HQJFuLk
S=A.H&^

Results (Encoded): b''
==========

========== the*2i"4
=:G e
========== password
<I=zsGi
Z)========== is
A=|t&E
Zdb=
c^ LAh=3G
*SF=s
&========== truKLdjsbJ5g7yyJ2X2R0o3a5HQJFuLk
S=A.H&^


==========
History

            Time Of Execution  ... Results Size (Bytes)
0  2021-11-09 14:47:11.832327  ...                  151

[1 rows x 5 columns]

#Bandit Level 10 ==> Level 11
--Level Goal--

The password for the next level is stored in the file data.txt, which contains base64 encoded data

--Commands you may need to solve this level--

grep, sort, uniq, strings, base64, tr, tar, gzip, bzip2, xxd


--Results--

Password: IFukwKGsFW8MOq3IRFqrxE1hxTNEbUPR

In [ ]:
import paramiko
import pandas as pd
import datetime
class SSH:
    def __init__(self,host,port,username,password):
        self.host=host
        self.port=port
        self.username=username
        self.password=password
        self.connection=self.__connect__()
        self.log={"Time Of Execution":[],"Command":[],"Results Decoded":[],"Results Encoded":[],"Results Size (Bytes)":[]}
    def __connect__(self):
        print("Starting Up SSH Client...")
        ssh=paramiko.SSHClient()
        print("Complete\nAdding Auto Add Policy...")
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        print("Complete\nAuthorizing Connection...")
        ssh.connect(self.host,port=self.port,username=self.username,password=self.password)
        print("Complete...\nConnected!\n==========\n\n")
        return ssh
    def Execute(self,command=None):
        print("Executing command: "+str(command))
        ssh_stdin, ssh_stdout, ssh_stderr = self.connection.exec_command(command)
        print("Command Executed...\nLogging Data...")
        Time=str(datetime.datetime.now())
        self.log["Time Of Execution"].append(Time)
        self.log["Command"].append(command)
        try:
            decoded_data=ssh_stdout.read().decode("ascii")
        except:
            decoded_data=None
        try:
            size=len(decoded_data)
        except:
            size=0
        self.log["Results Decoded"].append(decoded_data)
        self.log["Results Encoded"].append(repr(ssh_stdout.read()))
        self.log["Results Size (Bytes)"].append(size)
        print("Data Logged...\nComplete!\n\n--Executed Results--\nTime Of Execution: "+str(Time)+"\nCommand: "+command+"\nResults Size (Bytes): "+str(size)+"\nResults (Decoded): "+str(decoded_data)+"\nResults (Encoded): "+str(ssh_stdout.read())+"\n==========\n")
        return decoded_data
    def History(self):
        return pd.DataFrame(self.log)

print("Bandit: Level 10 -> Level 11\n==========")
server=SSH("bandit.labs.overthewire.org",2220,"bandit10","truKLdjsbJ5g7yyJ2X2R0o3a5HQJFuLk")
password=server.Execute('strings data.txt | base64 -d')
print(password)
print("\n==========\nHistory")
server.History()

Bandit: Level 10 -> Level 11
==========
Starting Up SSH Client...
Complete
Adding Auto Add Policy...
Complete
Authorizing Connection...
Complete...
Connected!
==========


Executing command: strings data.txt | base64 -d
Command Executed...
Logging Data...
Data Logged...
Complete!

--Executed Results--
Time Of Execution: 2021-11-09 14:53:40.588071
Command: strings data.txt | base64 -d
Results Size (Bytes): 49
Results (Decoded): The password is IFukwKGsFW8MOq3IRFqrxE1hxTNEbUPR

Results (Encoded): b''
==========

The password is IFukwKGsFW8MOq3IRFqrxE1hxTNEbUPR


==========
History

            Time Of Execution  ... Results Size (Bytes)
0  2021-11-09 14:53:40.588071  ...                   49

[1 rows x 5 columns]

#Bandit Level 11 ==> Level 12

--Level Goal--

The password for the next level is stored in the file data.txt, where all lowercase (a-z) and uppercase (A-Z) letters have been rotated by 13 positions


--Commands you may need to solve this level--

grep, sort, uniq, strings, base64, tr, tar, gzip, bzip2, xxd

--Helpful Reading Material--

Rot13 on Wikipedia

--Results--

Password: 5Te8Y4drgCRfCx8ugdwuEX8KFC6k2EUu

In [ ]:
import paramiko
import pandas as pd
import datetime
class SSH:
    def __init__(self,host,port,username,password):
        self.host=host
        self.port=port
        self.username=username
        self.password=password
        self.connection=self.__connect__()
        self.log={"Time Of Execution":[],"Command":[],"Results Decoded":[],"Results Encoded":[],"Results Size (Bytes)":[]}
    def __connect__(self):
        print("Starting Up SSH Client...")
        ssh=paramiko.SSHClient()
        print("Complete\nAdding Auto Add Policy...")
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        print("Complete\nAuthorizing Connection...")
        ssh.connect(self.host,port=self.port,username=self.username,password=self.password)
        print("Complete...\nConnected!\n==========\n\n")
        return ssh
    def Execute(self,command=None):
        print("Executing command: "+str(command))
        ssh_stdin, ssh_stdout, ssh_stderr = self.connection.exec_command(command)
        print("Command Executed...\nLogging Data...")
        Time=str(datetime.datetime.now())
        self.log["Time Of Execution"].append(Time)
        self.log["Command"].append(command)
        try:
            decoded_data=ssh_stdout.read().decode("ascii")
        except:
            decoded_data=None
        try:
            size=len(decoded_data)
        except:
            size=0
        self.log["Results Decoded"].append(decoded_data)
        self.log["Results Encoded"].append(repr(ssh_stdout.read()))
        self.log["Results Size (Bytes)"].append(size)
        print("Data Logged...\nComplete!\n\n--Executed Results--\nTime Of Execution: "+str(Time)+"\nCommand: "+command+"\nResults Size (Bytes): "+str(size)+"\nResults (Decoded): "+str(decoded_data)+"\nResults (Encoded): "+str(ssh_stdout.read())+"\n==========\n")
        return decoded_data
    def History(self):
        return pd.DataFrame(self.log)

print("Bandit: Level 11 -> Level 12\n==========")
server=SSH("bandit.labs.overthewire.org",2220,"bandit11","IFukwKGsFW8MOq3IRFqrxE1hxTNEbUPR")
password=server.Execute('strings data.txt | tr "A-Za-z" "N-ZA-Mn-za-m"')
print(password)
print("\n==========\nHistory")
server.History()

Bandit: Level 11 -> Level 12
==========
Starting Up SSH Client...
Complete
Adding Auto Add Policy...
Complete
Authorizing Connection...
Complete...
Connected!
==========


Executing command: strings data.txt | tr "A-Za-z" "N-ZA-Mn-za-m"
Command Executed...
Logging Data...
Data Logged...
Complete!

--Executed Results--
Time Of Execution: 2021-11-09 15:26:53.592462
Command: strings data.txt | tr "A-Za-z" "N-ZA-Mn-za-m"
Results Size (Bytes): 49
Results (Decoded): The password is 5Te8Y4drgCRfCx8ugdwuEX8KFC6k2EUu

Results (Encoded): b''
==========

The password is 5Te8Y4drgCRfCx8ugdwuEX8KFC6k2EUu


==========
History

            Time Of Execution  ... Results Size (Bytes)
0  2021-11-09 15:26:53.592462  ...                   49

[1 rows x 5 columns]